version: "2"
services:
  wildfly:
    build: .
    ports:
          - "8080:8080"
          - "9990:9990"
    depends_on:
      - neo4jdb
    network_mode: host
  neo4jdb:
    image: neo4j
    ports:
          - "7474:7474"
          - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      - NEO4J_AUTH=none
    network_mode: host